# Generated by Django 5.0.7 on 2024-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_user_alter_vote_vote_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlhackernews',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlhackernews',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crawlhackernews',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
