# Generated by Django 4.2.6 on 2024-07-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlhackernews',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='crawlhackernews',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vote',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.crawlhackernews'),
        ),
    ]
