# Generated by Django 4.2.6 on 2024-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_linksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlhackernews',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
