# Generated by Django 4.2.6 on 2024-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_comment_comment_form_text_comment_form_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_form',
            name='comment',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
    ]
