# Generated by Django 4.2.6 on 2024-07-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_comment_form_news_remove_comment_form_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
    ]
