# Generated by Django 4.2.6 on 2024-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_comment_parent_alter_comment_news_delete_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_form',
            old_name='comment',
            new_name='text',
        ),
    ]
