# Generated by Django 4.2.6 on 2024-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_rename_comment_comment_form_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_form',
            old_name='text',
            new_name='text',
        ),
    ]
